#!/bin/bash
# Quality Check Stop Hook
# Auto-generated by stop-hook-builder skill
#
# This script runs quality checks in order of speed.
# Stops at first failure to provide immediate feedback.

set -e  # Exit on error

# Color output for readability
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to run a check and report result
run_check() {
  local name="$1"
  local command="$2"

  echo -e "${YELLOW}Running: $name${NC}"
  if eval "$command"; then
    echo -e "${GREEN}✓ $name passed${NC}"
    return 0
  else
    echo -e "${RED}✗ $name failed${NC}"
    return 1
  fi
}

# Change to project directory
cd "$CLAUDE_PROJECT_DIR" || exit 1

# Fast checks - run on every stop
{{FAST_CHECKS}}

# Medium checks - run if enabled
{{MEDIUM_CHECKS}}

# Slow checks - run if explicitly enabled
{{SLOW_CHECKS}}

echo -e "${GREEN}All quality checks passed!${NC}"
exit 0
